version: '3.7'

services:
  hello-service:
    build:
      context: ./services/hello-world
    container_name: hello-service
    env_file:
      - ./services/hello-world/.env
    ports:
      - '4000:4000'
  quote-service:
    build:
      context: ./services/quote
    container_name: quote-service
    env_file:
      - ./services/quote/.env
    ports:
      - '6000:6000'
  api-gateway:
    build:
      context: ./services/gateway
    container_name: api-gateway
    environment:
      - NODE_ENV=prod
    ports:
      - '5000:5000'
