version: '3.7'

services:
  hello-service:
    build:
      context: ./services/hello-world
    image: ${CONTAINER_REGISTRY}/hello-service:${GIT_SHA}
    container_name: hello-service
    ports:
      - '4000:4000'
  quote-service:
    build:
      context: ./services/quote
    image: ${CONTAINER_REGISTRY}/quote-service:${GIT_SHA}
    container_name: quote-service
    ports:
      - '6000:6000'
  api-gateway:
    build:
      context: ./services/gateway
    image: ${CONTAINER_REGISTRY}/api-gateway:${GIT_SHA}
    container_name: api-gateway
    environment:
      - NODE_ENV=prod
    ports:
      - '5000:5000'
  frontend:
    build:
      context: ./frontend
    image: ${CONTAINER_REGISTRY}/frontend:${GIT_SHA}
    container_name: frontend
    ports:
      - '5173:5173'
