version: '3.7'

services:
  hello-service:
    build:
      context: ./services/hello-world
    image: ${CONTAINER_REGISTRY}/hello-service:${GIT_SHA}
    container_name: hello-service
    ports:
      - '4000:4000'
  quote-service:
    build:
      context: ./services/quote
    image: ${CONTAINER_REGISTRY}/quote-service:${GIT_SHA}
    container_name: quote-service
    ports:
      - '6000:6000'
