replicaCount: 1

cosmos_uri: ""

image:
  regitry: ""
  repository: quote-service
  pullPolicy: IfNotPresent
  tag: ""

service:
  type: ClusterIP
  port: 80

ingress:
  className: nginx
  enabled: true
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
  hosts:
    - host: quote-service.microserviceslab.io
      paths:
        - path: /quote
          pathType: Prefix

  tls:
   - secretName: keyvault-quote-service
     hosts:
       - quote-service.microserviceslab.io

secrets:
 - name: COSMOS_URI
   secretKeyRef:
    name: quote-database
    key: cosmos_uri

resources:
  limits:
    cpu: 250m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}