replicaCount: 1

image:
  regitry: ""
  repository: hello-service
  pullPolicy: IfNotPresent
  tag: ""

service:
  type: ClusterIP
  port: 80

ingress:
  className: webapprouting.kubernetes.azure.com
  enabled: true
  annotations:
    kubernetes.azure.com/tls-cert-keyvault-uri: https://microserviceslab-kvault.vault.azure.net/certificates/hello-service-cert/cb1a84bfd68d4976bee2b10889a9eb85
  hosts:
    - host: hello-service.6f449b07363b4e2eb07c.southeastasia.aksapp.io
      paths:
        - path: /
          pathType: Prefix

  tls:
   - secretName: keyvault-hello-service
     hosts:
       - hello-service.6f449b07363b4e2eb07c.southeastasia.aksapp.io

resources:
  limits:
    cpu: 250m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}