replicaCount: 1

image:
  regitry: ""
  repository: hello-service
  pullPolicy: IfNotPresent
  tag: ""

service:
  type: ClusterIP
  port: 80

ingress:
  className: nginx
  enabled: true
  annotations:
    kubernetes.azure.com/tls-cert-keyvault-uri: https://microserviceslab-kvault.vault.azure.net/certificates/hello-service-cert/3221569f62894aee82c790c2c7667636
  hosts:
    - host: hello-service.microserviceslab.io
      paths:
        - path: /
          pathType: Prefix

  tls:
   - secretName: keyvault-hello-service
     hosts:
       - hello-service.microserviceslab.io

secrets:
 - name: COSMOS_URI
   secretKeyRef:
    name: hello-database
    key: cosmos_uri

resources:
  limits:
    cpu: 250m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}