replicaCount: 1

image:
  regitry: ""
  repository: hello-service
  pullPolicy: IfNotPresent
  tag: ""

service:
  type: ClusterIP
  port: 80

ingress:
  className: nginx
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  hosts:
    - host: hello-service.microserviceslab.io
      paths:
        - path: /
          pathType: Prefix

  tls:
   - secretName: ingress-tls-csi
     hosts:
       - hello-service.microserviceslab.io

akv:
  name: microserviceslab-kvault
  tenantId: a3ff8926-c642-4722-85a2-246eb3098a3c

secrets:
 - name: COSMOS_URI
   secretKeyRef:
    name: hello-database
    key: cosmos_uri

resources:
  limits:
    cpu: 250m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}