apiVersion: v1
kind: Secret
metadata:
  name: hello-database
  namespace: default
type: Opaque
stringData:
  mongo_uri: "mongodb://microserviceslab-db:umHMWVzzfqz3MYknxJWzyYOHf2y1JbTqY5n4UoSLGFI7uL7rBhctWJEsGsUpx4n0cRMTg0ADqkj3ACDbi9ueEQ%3D%3D@microserviceslab-db.mongo.cosmos.azure.com:10255/?ssl=true&retrywrites=false&maxIdleTimeMS=120000&appName=@microserviceslab-db@"