name: Microservices Lab

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  # basic
  resourceGroup: microservices-lab
  location: southeastasia
  aca-environment: microserviceslab-aca-env

  # aci
  hello_image_name: hello-service
  quote_image_name: quote-service

jobs:
  build:
    name: Build / Push to ACR
    runs-on: ubuntu-latest
    steps:
      # checkout branch
      - name: git checkout main branch
        uses: actions/checkout@v3

      # log into Azure
      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'docker login'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.CONTAINER_REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: 'docker compose build'
        run: export CONTAINER_REGISTRY=${{secrets.CONTAINER_REGISTRY}} GIT_SHA=${{github.sha}} && docker compose build

      - name: 'docker compose push'
        run: export CONTAINER_REGISTRY=${{secrets.CONTAINER_REGISTRY}} GIT_SHA=${{github.sha}} && docker compose push

  deploy:
    name: Deploy to ACA
    runs-on: ubuntu-latest
    needs: build
    steps:
      # checkout branch
      - name: git checkout main branch
        uses: actions/checkout@v2

      # log into Azure
      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Deploy Hello Service to ACA'
        uses: 'azure/container-apps-deploy-action@v1'
        with:
          imageToDeploy: ${{ secrets.CONTAINER_REGISTRY }}/hello-service:${{ github.sha }}
          acrName: microserviceslab
          acrUsername: ${{ secrets.REGISTRY_USERNAME }}
          acrPassword: ${{ secrets.REGISTRY_PASSWORD }}
          containerAppName: ${{ env.hello_image_name }}
          resourceGroup: ${{ env.resourceGroup }}
          containerAppEnvironment: ${{ env.aca-environment }}
          location: ${{ env.location }}
          targetPort: 4000
          ingress: external
          environmentVariables: |
            COSMOS_URI=${{ secrets.COSMOS_URI }}

      - name: 'Deploy Quote Service to ACA'
        uses: 'azure/container-apps-deploy-action@v1'
        with:
          imageToDeploy: ${{ secrets.CONTAINER_REGISTRY }}/quote-service:${{ github.sha }}
          acrName: microserviceslab
          acrUsername: ${{ secrets.REGISTRY_USERNAME }}
          acrPassword: ${{ secrets.REGISTRY_PASSWORD }}
          containerAppName: ${{ env.quote_image_name }}
          resourceGroup: ${{ env.resourceGroup }}
          containerAppEnvironment: ${{ env.aca-environment }}
          location: ${{ env.location }}
          targetPort: 6000
          ingress: external
          environmentVariables: |
            COSMOS_URI=${{ secrets.COSMOS_URI }}
